/* ============ TerryLand 修仙 官網資料 ============ */
/* 資料來源：src/data/* 及 src/features/*（與遊戲實際設定同步） */

const DATA = {
  // ===== 境界 =====
  realms: [
    { name: '凡人',   stage: '起點',   threshold: '0',      rate: '—' },
    { name: '練氣',   stage: '1-12層', threshold: '200~2400', rate: '70%' },
    { name: '築基',   stage: '初/中/後', threshold: '3000~5000', rate: '50%' },
    { name: '結丹',   stage: '初/中/後', threshold: '7000~11000', rate: '40%' },
    { name: '元嬰',   stage: '初/中/後', threshold: '15000~24000', rate: '20%' },
    { name: '化神',   stage: '初/中/後', threshold: '30000~42000', rate: '15%' },
    { name: '煉虛',   stage: '初/中/後', threshold: '52000~72000', rate: '10%' },
    { name: '合體',   stage: '初/中/後', threshold: '87000~120000', rate: '5%' },
    { name: '大乘',   stage: '無',     threshold: '120000', rate: '—' },
    { name: '真仙',   stage: '無',     threshold: '150000', rate: '—' },
  ],

  realmSpecial: [
    { realm: '結丹→元嬰', need: '心魔劫', desc: '必須作答心魔問題，道心堅定方能通過（30 秒內回覆 Y/N）' },
    { realm: '化神→煉虛', need: '五行合一', desc: '需集齊金木水火土五種靈根（光代金、暗代土），由五行妖神谷試煉補全' },
    { realm: '大乘→真仙', need: '九道雷劫', desc: '以回合制戰鬥扛過九道天劫（總傷害 180% 最大生命），渡劫丹/噬天吸雷珠可減傷' },
  ],

  roots: [
    { type: '天靈根', rate: '10%', roots: '單一屬性（5% 為稀有光/暗）', speed: 'x1.5' },
    { type: '一般靈根', rate: '50%', roots: '1-3 種屬性', speed: 'x1.3~1.5' },
    { type: '偽靈根', rate: '40%', roots: '4-5 種屬性', speed: 'x0.9~1.1' },
  ],
  rootNote: '靈根越多速度越低（每多一個 -0.2），但五行合一可突破煉虛。天靈根練氣/築基階段突破必定成功。',

  // ===== 功法 =====
  techniques: [
    // 中階
    { name: '金罡玄功', tier: '中階', element: '金', desc: '攻擊時20%機率破甲（無視30%防禦，2回合）', stats: ['攻擊+10%'], effect: ['破甲'] },
    { name: '金剛伏魔功', tier: '中階', element: '金', desc: '對暗系+20%傷害，被攻擊15%反彈30%', stats: ['攻擊+8%','防禦+8%'], effect: ['反彈30%','對暗增傷'] },
    { name: '太白劍訣', tier: '中階', element: '金', desc: '攻擊時25%機率流血（每回合8%最大生命，2回合）', stats: ['攻擊+15%'], effect: ['流血'] },
    { name: '萬木生靈訣', tier: '中階', element: '木', desc: '每回合回4%生命，治療效果+20%', stats: ['生命+10%','防禦+5%'], effect: ['回血','治療加成'] },
    { name: '枯木逢春功', tier: '中階', element: '木', desc: '生命<30%觸發回10%生命(3回合)，每場一次', stats: ['生命+15%'], effect: ['低血回血'] },
    { name: '弱水三千訣', tier: '中階', element: '水', desc: '攻擊時20%機率虛弱（對方傷害減半，2回合）', stats: ['防禦+15%'], effect: ['虛弱'] },
    { name: '寒冰凝玉功', tier: '中階', element: '水', desc: '攻擊時20%機率冰凍', stats: ['防禦+10%','生命+5%'], effect: ['冰凍'] },
    { name: '赤陽心法', tier: '中階', element: '火', desc: '暴擊時30%機率燃燒（10%最大生命，2回合）', stats: ['攻擊+10%','暴擊+5%'], effect: ['燃燒'] },
    { name: '紅蓮業火訣', tier: '中階', element: '火', desc: '攻擊時25%機率燃燒（12%最大生命，2回合）', stats: ['攻擊+15%'], effect: ['燃燒'] },
    { name: '地元靈訣', tier: '中階', element: '土', desc: '被攻擊25%機率獲護盾（20%最大生命，2回合）', stats: ['生命+10%','防禦+10%'], effect: ['護盾'] },
    { name: '玄黃厚土經', tier: '中階', element: '土', desc: '防禦+15%，被攻擊反彈15%', stats: ['防禦+20%'], effect: ['反彈15%'] },
    { name: '大日靈光訣', tier: '中階', element: '光', desc: '攻擊時20%機率淨化自身並回5%生命', stats: ['生命+5%','攻擊+5%'], effect: ['淨化'] },
    { name: '太陰真經', tier: '中階', element: '暗', desc: '攻擊時20%機率詛咒（每回合3%最大生命，3回合）', stats: ['攻擊+10%','暴擊+5%'], effect: ['詛咒'] },
    { name: '凝神決', tier: '中階', element: '水', desc: '神識+15%', stats: ['神識+15%'], effect: [] },
    { name: '疾影功', tier: '中階', element: '暗', desc: '遁速+15%', stats: ['遁速+15%'], effect: [] },
    { name: '破甲劍經', tier: '中階', element: '金', desc: '攻擊20%機率破甲', stats: ['穿透+10%'], effect: ['破甲'] },
    { name: '烈焰心訣', tier: '中階', element: '火', desc: '暴擊時20%機率燃燒', stats: ['暴擊+5%'], effect: ['燃燒'] },
    { name: '金銳真解', tier: '中階', element: '金', desc: '暴擊傷害+10%', stats: ['暴傷+10%'], effect: [] },
    // 高階
    { name: '明王訣', tier: '高階', element: '金', desc: '攻擊時20%機率震懾（下回合傷害-30%）', stats: ['攻擊+20%','防禦+10%'], effect: ['震懾'] },
    { name: '大衍訣', tier: '高階', element: '金', desc: '每命中疊3%攻擊（最高5層）', stats: ['攻擊+15%','暴擊+5%','神識+15%'], effect: ['疊攻'] },
    { name: '古神訣', tier: '高階', element: '金', desc: '生命<50%時攻擊+30%並獲20%吸血', stats: ['攻擊+25%','生命+10%'], effect: ['狂暴','吸血'] },
    { name: '青元劍訣', tier: '高階', element: '木', desc: '攻擊時25%機率150%傷害+破甲', stats: ['攻擊+15%','生命+10%'], effect: ['150%傷害','破甲'] },
    { name: '如來大乘經', tier: '高階', element: '木', desc: '每回合回5%生命，生命<30%獲金身(減傷50%)', stats: ['生命+20%','防禦+15%'], effect: ['回血','金身'] },
    { name: '六極真魔功', tier: '高階', element: '水', desc: '攻擊15%機率130%傷害+虛弱；被攻擊15%反彈30%', stats: ['攻擊+15%','防禦+15%'], effect: ['虛弱','反彈30%'] },
    { name: '玄陰經', tier: '高階', element: '水', desc: '攻擊25%機率冰凍（冰凍時額外+30%傷害）', stats: ['防禦+20%','生命+10%'], effect: ['冰凍'] },
    { name: '黃泉升竅訣', tier: '高階', element: '水', desc: '每擊殺永久+2%攻擊（上限20%），擊殺回20%生命', stats: ['攻擊+20%'], effect: ['擊殺成長','擊殺回血'] },
    { name: '鳳凰涅槃火', tier: '高階', element: '火', desc: '死亡時涅槃（回50%生命+攻+30%，3回合），每場一次', stats: ['攻擊+20%','暴擊+5%'], effect: ['涅槃復活'] },
    { name: '朱雀焚天錄', tier: '高階', element: '火', desc: '暴擊必定燃燒（15%最大生命，2回合）', stats: ['攻擊+20%','暴擊+10%'], effect: ['燃燒'] },
    { name: '拓天魔功', tier: '高階', element: '土', desc: '被攻擊20%機率反彈40%', stats: ['防禦+25%','生命+10%'], effect: ['反彈40%'] },
    { name: '披甲龍龜功', tier: '高階', element: '土', desc: '開局獲護盾（30%最大生命），護盾在時減傷20%', stats: ['防禦+20%','生命+20%'], effect: ['開局護盾','減傷'] },
    { name: '驚蟄十二變', tier: '高階', element: '土', desc: '每回合10%機率真靈變身（青龍/白虎/玄武/朱雀）', stats: ['全屬性+10%'], effect: ['變身'] },
    { name: '九陽天照訣', tier: '高階', element: '光', desc: '攻擊20%機率200%傷害+燃燒', stats: ['攻擊+20%','暴擊+5%'], effect: ['200%傷害','燃燒'] },
    { name: '光明淨世訣', tier: '高階', element: '光', desc: '每回合25%機率淨化並回10%生命', stats: ['生命+15%','防禦+15%'], effect: ['淨化','回血'] },
    { name: '元磁神光', tier: '高階', element: '光', desc: '被攻擊25%機率反彈50%並降對方20%攻擊', stats: ['防禦+20%','生命+10%'], effect: ['反彈50%','降攻'] },
    { name: '九幽冥王訣', tier: '高階', element: '暗', desc: '攻擊20%機率130%傷害+震懾', stats: ['攻擊+20%','暴擊+5%'], effect: ['震懾'] },
    { name: '萬鬼噬心功', tier: '高階', element: '暗', desc: '攻擊30%機率120%傷害並回50%傷害生命', stats: ['攻擊+15%','生命+15%'], effect: ['噬心吸血'] },
    { name: '觀天心法', tier: '高階', element: '水', desc: '神識+25%', stats: ['神識+25%'], effect: [] },
    { name: '縮地神行', tier: '高階', element: '暗', desc: '遁速+20%，閃避+10%', stats: ['遁速+20%','閃避+10%'], effect: [] },
    { name: '透骨經', tier: '高階', element: '金', desc: '攻擊20%機率破甲', stats: ['穿透+15%'], effect: ['破甲'] },
    { name: '焚天真火功', tier: '高階', element: '火', desc: '暴擊時30%機率燃燒', stats: ['暴擊+8%','暴傷+8%'], effect: ['燃燒'] },
    { name: '斬神劍意', tier: '高階', element: '金', desc: '暴擊傷害+20%', stats: ['暴傷+20%'], effect: [] },
    { name: '不動明王身', tier: '高階', element: '土', desc: '被攻擊20%機率獲護盾', stats: ['免疫負面+20%','防禦+10%'], effect: ['護盾'] },
    // 頂級
    { name: '梵聖真魔功', tier: '頂級', element: '金', desc: '被攻擊減傷20%；每回合30%機率真魔法相（攻x2+50%吸血）', stats: ['攻擊+30%','防禦+20%','生命+15%'], effect: ['減傷','法相爆發'], unique: false },
    { name: '九龍帝皇功', tier: '頂級', element: '金', desc: '攻擊30%機率200%傷害+震懾+自身攻+20%', stats: ['攻擊+30%','暴擊+10%','生命+10%'], effect: ['200%傷害','震懾'], unique: false },
    { name: '萬古菩提經', tier: '頂級', element: '木', desc: '每回合回8%生命；生命<30%金身（減傷60%免疫負面）', stats: ['生命+30%','防禦+20%'], effect: ['回血','金身'], unique: false },
    { name: '大五行幻世訣', tier: '頂級', element: '木', desc: '每回合20%機率五行幻世（金木水火土隨機效果）', stats: ['全屬性+20%'], effect: ['五行幻世'], unique: false },
    { name: '滄海一聲笑', tier: '頂級', element: '水', desc: '攻擊30%機率180%傷害+虛弱+冰凍', stats: ['防禦+25%','攻擊+20%'], effect: ['180%傷害','虛弱','冰凍'], unique: false },
    { name: '大育天魔經', tier: '頂級', element: '水', desc: '每回合25%機率天魔化生（複製增益+隨機負面）', stats: ['全屬性+15%','攻擊+15%'], effect: ['天魔化生'], unique: false },
    { name: '混沌涅槃經', tier: '頂級', element: '火', desc: '死亡時混沌涅槃（回滿血+攻50%+吸血50%，3回合）', stats: ['攻擊+35%','暴擊+15%','生命+15%'], effect: ['涅槃復活'], unique: false },
    { name: '盤古開天經', tier: '頂級', element: '土', desc: '被攻擊30%機率反彈60%+震懾', stats: ['防禦+35%','生命+30%'], effect: ['反彈60%','震懾'], unique: false },
    { name: '道劍十四篇', tier: '頂級', element: '光', desc: '攻擊25%機率250%傷害+驅散增益，對暗系300%', stats: ['攻擊+30%','暴擊+15%','防禦+10%'], effect: ['250%傷害','驅散'], unique: false },
    { name: '黃泉渡魂經', tier: '頂級', element: '暗', desc: '攻擊25%機率200%傷害+斬殺<15%生命；擊殺永久+3%攻擊', stats: ['攻擊+30%','暴擊+10%'], effect: ['斬殺','擊殺成長'], unique: false },
    { name: '殺戮仙訣', tier: '頂級', element: '暗', desc: '每擊殺永久+5%攻擊（上限50%）並回30%生命；攻擊30%機率180%傷害', stats: ['攻擊+35%','暴擊+15%','生命+10%'], effect: ['擊殺成長','擊殺回血'], unique: false },
    { name: '雷神降世訣', tier: '頂級', element: '金', desc: '攻擊30%機率150%傷害+麻痹+虛弱', stats: ['攻擊+30%','暴擊+10%'], effect: ['麻痹','虛弱'], unique: false },
    { name: '太虛神遊', tier: '頂級', element: '水', desc: '神識+40%，每回合30%機率淨化', stats: ['神識+40%'], effect: ['淨化'], unique: false },
    { name: '咫尺天涯', tier: '頂級', element: '暗', desc: '遁速+30%，閃避+15%', stats: ['遁速+30%','閃避+15%'], effect: [], unique: false },
    { name: '虛無寂滅指', tier: '頂級', element: '金', desc: '攻擊25%機率破甲', stats: ['穿透+25%'], effect: ['破甲'], unique: false },
    { name: '九陽焚天', tier: '頂級', element: '火', desc: '暴擊必定燃燒', stats: ['暴擊+15%','暴傷+15%'], effect: ['燃燒'], unique: false },
    { name: '無垢金身', tier: '頂級', element: '光', desc: '免疫負面+30%，每回合10%機率淨化', stats: ['免疫負面+30%','防禦+10%'], effect: ['淨化'], unique: false },
    { name: '王八陀螺功', tier: '頂級', element: '土', desc: '被攻擊50%機率反彈30%並獲護盾（10%最大生命）', stats: ['防禦+35%','生命+20%'], effect: ['反彈30%','護盾'], unique: false },
    { name: '馮母鞭法', tier: '頂級', element: '暗', desc: '攻擊30%機率鞭掃（180%傷害+震懾+斬殺<10%生命）', stats: ['暴擊+15%','暴傷+20%'], effect: ['鞭掃','震懾','斬殺10%'], unique: false },
  ],

  techniqueNote: '功法需同屬性靈根才能修練為主/副功法。主功法效果全額、副功法效果為一半（結丹起可修練副功法）。獲得的功法屬性不符時可先存放，補全靈根後即可修練。',

  // ===== 法寶 =====
  treasures: [
    { name: '青鋒劍', tier: '低階', type: '攻擊型', desc: '攻擊力+8%' },
    { name: '多蘭劍', tier: '低階', type: '攻擊型', desc: '攻擊力+5%' },
    { name: '多蘭盾', tier: '低階', type: '防禦型', desc: '防禦力+8%' },
    { name: '金光磚', tier: '低階', type: '攻擊型', desc: '攻擊10%機率150%傷害' },
    { name: '迷蹤鐘', tier: '低階', type: '輔助型', desc: '被攻擊10%機率使對方混亂' },
    { name: '玄鐵盾', tier: '低階', type: '防禦型', desc: '防禦+10%，生命<30%減傷30%' },
    { name: '寒冰針', tier: '低階', type: '攻擊型', desc: '攻擊15%機率冰凍' },
    { name: '烈焰環', tier: '低階', type: '攻擊型', desc: '攻擊15%機率燃燒（10%最大生命）' },
    { name: '玄水珠', tier: '低階', type: '輔助型', desc: '神識+10%' },
    { name: '疾風履', tier: '低階', type: '輔助型', desc: '遁速+15%' },
    { name: '破陣鈴', tier: '低階', type: '攻擊型', desc: '穿透+8%' },
    { name: '赤血刃', tier: '低階', type: '攻擊型', desc: '暴擊+5%' },
    { name: '銳金符', tier: '低階', type: '攻擊型', desc: '暴傷+10%' },
    { name: '清心鈴', tier: '低階', type: '輔助型', desc: '免疫負面+10%' },
    { name: '鎮魂木', tier: '低階', type: '輔助型', desc: '對靈體+30%傷害' },
    { name: '綠煌劍', tier: '中階', type: '攻擊型', desc: '攻擊20%機率120%傷害+降對方10%攻擊' },
    { name: '混元缽', tier: '中階', type: '防禦型', desc: '防禦+10%，被攻擊15%獲護盾' },
    { name: '火雲劍', tier: '中階', type: '攻擊型', desc: '攻擊+10%，攻擊20%燃燒' },
    { name: '烏龍奪', tier: '中階', type: '攻擊型', desc: '攻擊20%破甲（降15%防禦）' },
    { name: '血煞刀', tier: '中階', type: '攻擊型', desc: '攻擊+12%，吸血20%' },
    { name: '血魔錐', tier: '中階', type: '攻擊型', desc: '攻擊+10%，10%機率200%傷害' },
    { name: '金蚨子母刃', tier: '中階', type: '攻擊型', desc: '攻擊+10%，20%機率150%傷害' },
    { name: '七情六欲幡', tier: '中階', type: '輔助型', desc: '攻擊15%機率混亂' },
    { name: '玄冰珠', tier: '中階', type: '攻擊型', desc: '攻擊20%機率冰凍' },
    { name: '困龍索', tier: '中階', type: '輔助型', desc: '攻擊15%機率麻痹' },
    { name: '滅魂針', tier: '中階', type: '攻擊型', desc: '攻擊20%機率150%傷害，對靈體200%' },
    { name: '紫金紅葫蘆', tier: '中階', type: '輔助型', desc: '攻擊5%機率封印2回合（BOSS無效）' },
    { name: '靈犀鏡', tier: '中階', type: '輔助型', desc: '神識+15%' },
    { name: '踏雲履', tier: '中階', type: '輔助型', desc: '遁速+20%' },
    { name: '穿雲梭', tier: '中階', type: '攻擊型', desc: '穿透+12%' },
    { name: '星火戒', tier: '中階', type: '攻擊型', desc: '暴擊+8%' },
    { name: '斬風劍', tier: '中階', type: '攻擊型', desc: '暴傷+15%' },
    { name: '黑風旗', tier: '中階', type: '輔助型', desc: '降低對方10%閃避' },
    { name: '五行環', tier: '高階', type: '全能型', desc: '全屬性+5%，每回合隨機五行效果' },
    { name: '婆羅珠', tier: '高階', type: '輔助型', desc: '每回合回5%最大生命' },
    { name: '皇鱗甲', tier: '高階', type: '防禦型', desc: '防禦+15%，被攻擊20%減傷30%' },
    { name: '青冥針', tier: '高階', type: '攻擊型', desc: '攻擊25%機率150%傷害+中毒' },
    { name: '朱雀環', tier: '高階', type: '攻擊型', desc: '暴擊+10%，暴擊必定燃燒' },
    { name: '嗜血者', tier: '高階', type: '攻擊型', desc: '攻擊+15%，吸血30%（低血時50%）' },
    { name: '方天畫戟', tier: '高階', type: '攻擊型', desc: '攻擊+15%，20%機率150%傷害+震懾' },
    { name: '青龍偃月刀', tier: '高階', type: '攻擊型', desc: '攻擊+15%，20%機率180%傷害' },
    { name: '青竹蜂雲劍', tier: '高階', type: '攻擊型', desc: '攻擊+10%，25%機率160%傷害+破甲' },
    { name: '北斗七星劍', tier: '高階', type: '攻擊型', desc: '攻擊+12%，20%機率200%傷害，對暗系+50%' },
    { name: '七殺劍', tier: '高階', type: '攻擊型', desc: '攻擊+20%，15%機率250%傷害（自損5%）' },
    { name: '天機盤', tier: '高階', type: '輔助型', desc: '神識+20%' },
    { name: '縮地靴', tier: '高階', type: '輔助型', desc: '遁速+25%' },
    { name: '破甲錐', tier: '高階', type: '攻擊型', desc: '穿透+18%' },
    { name: '熾陽環', tier: '高階', type: '攻擊型', desc: '暴擊+12%' },
    { name: '影殺刃', tier: '高階', type: '攻擊型', desc: '暴傷+20%' },
    { name: '鎮魂塔', tier: '高階', type: '輔助型', desc: '免疫負面+20%，5%機率淨化' },
    { name: '馮問的魔丸', tier: '高階', type: '特殊型', desc: '開局自損99%生命（留1），使對方暈2回合' },
    { name: '風雷翅', tier: '頂級', type: '輔助型', desc: '閃避+15%（額外+15%）', unique: true },
    { name: '暴雨梨花針', tier: '頂級', type: '攻擊型', desc: '攻擊30%機率連攻3次（每次70%）', unique: true },
    { name: '血魔劍', tier: '頂級', type: '攻擊型', desc: '攻擊+20%，吸血25%，10%機率250%血爆', unique: true },
    { name: '射神車', tier: '頂級', type: '攻擊型', desc: '攻擊20%機率250%傷害+震懾', unique: true },
    { name: '八門金光鏡', tier: '頂級', type: '攻擊型', desc: '攻擊+20%，25%機率300%傷害，對暗系+100%', unique: true },
    { name: '定海神針', tier: '頂級', type: '攻擊型', desc: '攻擊+25%，20%機率200%傷害+冰凍+虛弱', unique: true },
    { name: '九齒釘耙', tier: '頂級', type: '攻擊型', desc: '攻擊+15%，被攻擊20%反彈40%+降攻', unique: true },
    { name: '五子同心魔', tier: '頂級', type: '輔助型', desc: '攻擊25%機率150%傷害+吸10%最大生命', unique: true },
    { name: '萬里山河圖', tier: '頂級', type: '控制型', desc: '攻擊30%機率鎮壓2回合（BOSS 1回合）', unique: true },
    { name: '九幽白骨幡', tier: '頂級', type: '攻擊型', desc: '攻擊+20%，20%機率200%傷害+詛咒', unique: true },
    { name: '軒轅劍', tier: '頂級', type: '攻擊型', desc: '攻擊+25%，對暗系+50%，20%機率驅散', unique: true },
    { name: '伏羲琴', tier: '頂級', type: '控制型', desc: '攻擊15%混亂；被攻擊15%使對方睡眠', unique: true },
    { name: '崑崙鏡', tier: '頂級', type: '輔助型', desc: '被攻擊15%複製增益；10%機率閃避致命傷', unique: true },
    { name: '黃泉圖', tier: '頂級', type: '攻擊型', desc: '攻擊25%機率200%傷害+斬殺<20%生命', unique: true },
    { name: '太虛鏡', tier: '頂級', type: '輔助型', desc: '神識+30%', unique: true },
    { name: '瞬息萬里', tier: '頂級', type: '輔助型', desc: '遁速+30%', unique: true },
    { name: '無相破妄針', tier: '頂級', type: '攻擊型', desc: '穿透+25%', unique: true },
    { name: '雷火令', tier: '頂級', type: '攻擊型', desc: '暴擊+15%，暴傷+15%', unique: true },
    { name: '滅世紅蓮', tier: '頂級', type: '攻擊型', desc: '暴傷+30%', unique: true },
    { name: '噬天吸雷珠', tier: '頂級', type: '防禦型', desc: '雷劫傷害-20%，攻擊25%麻痹', unique: true },
    { name: '虛天鼎', tier: '通天靈寶', type: '全能型', desc: '攻/防+20%，每回合回5%，20%機率250%傷害+吸血', unique: true },
    { name: '十億尊魂幡', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+25%，30%機率300%傷害+詛咒', unique: true },
    { name: '雨之仙劍', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+30%，25%機率250%傷害+冰凍+虛弱', unique: true },
    { name: '滅神矛', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+30%，25%機率300%傷害，無視50%防禦', unique: true },
    { name: '掌天瓶', tier: '通天靈寶', type: '輔助型', desc: '修練速度+100%，靈草種植/成熟速度+200%，戰鬥中每回合回復8%最大生命', unique: true },
    { name: '天逆珠', tier: '通天靈寶', type: '全能型', desc: '全屬性+15%，20%機率時間加速（行動兩次）', unique: true },
    { name: '萬妖塔', tier: '通天靈寶', type: '防禦型', desc: '防禦+30%，被攻擊25%反彈50%+護盾', unique: true },
    { name: '元合五極山', tier: '通天靈寶', type: '全能型', desc: '全屬性+20%，每回合五行鎮壓', unique: true },
    { name: '佛怒唐蓮', tier: '通天靈寶', type: '攻擊型', desc: '開局造成對方30%最大生命傷害', unique: true },
    { name: '玄天斬靈劍', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+30%，對靈體+100%，25%機率斬殺<25%', unique: true },
    { name: '七焰扇', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+25%，25%機率300%傷害+燃燒，對暗+50%', unique: true },
    { name: '八靈尺', tier: '通天靈寶', type: '控制型', desc: '攻擊20%隨機控場；被攻擊15%獲護盾', unique: true },
    { name: '誅仙四劍', tier: '通天靈寶', type: '攻擊型', desc: '攻擊+35%，30%機率400%傷害+震懾+破甲', unique: true },
    { name: '太初神燈', tier: '通天靈寶', type: '全能型', desc: '攻擊+20%，每回合回5%，20%機率300%傷害+驅散', unique: true },
    { name: '輪迴盤', tier: '通天靈寶', type: '控制型', desc: '攻擊25%機率200%傷害+混亂2回合', unique: true },
    { name: '東皇鐘', tier: '通天靈寶', type: '全能型', desc: '全屬性+15%，被攻擊25%減傷50%+反彈30%', unique: true },
    { name: '破滅神瞳', tier: '通天靈寶', type: '全能型', desc: '全屬性+15%，穿透+20%，神識+20%', unique: true },
    { name: '生死簿', tier: '通天靈寶', type: '特殊型', desc: '攻擊15%機率斬殺<30%；被擊殺20%機率續命', unique: true },
    { name: '馮母伏豬鞭', tier: '通天靈寶', type: '攻擊型', desc: '暴擊+30%，暴傷+30%，吸血40%', unique: true },
  ],

  treasureNote: '頂級法寶與通天靈寶皆為「獨一無二」：全服僅此一件，先到先得，一旦有人持有便絕版。被搶先時獲得方會收到同階級其他法寶或靈石補償。',

  // ===== 奇遇 =====
  adventure: {
    cooldown: '6 小時',
    pools: [
      { id: 'special', name: '特殊池', rate: '1%', items: [
        { name: '通天靈寶', rate: '0.1%', desc: '獨一無二至寶' },
        { name: '頂級法寶', rate: '0.2%', desc: '獨一無二' },
        { name: '天選之人', rate: '0.1%', desc: '獲得稱號「天選之人」' },
        { name: '頂級功法', rate: '0.1%', desc: '屬性匹配' },
        { name: '高階功法', rate: '0.3%', desc: '' },
        { name: '高階丹藥', rate: '0.2%', desc: '化神以上' },
      ] },
      { id: 'high', name: '高級池', rate: '19%', items: [
        { name: '結丹/元嬰靈草', rate: '6%', desc: '' },
        { name: '結丹/元嬰丹藥', rate: '5%', desc: '' },
        { name: '中階法寶', rate: '3%', desc: '' },
        { name: '高階法寶', rate: '2%', desc: '' },
        { name: '中階功法', rate: '2%', desc: '' },
        { name: '高階資材', rate: '1%', desc: '' },
      ] },
      { id: 'low', name: '普通池', rate: '80%', items: [
        { name: '靈石', rate: '14.5%', desc: '100-500' },
        { name: '修爲', rate: '12%', desc: '總修爲+2~5%' },
        { name: '練氣/築基靈草', rate: '12%', desc: '' },
        { name: '無事發生', rate: '10%', desc: '' },
        { name: '練氣/築基丹藥', rate: '8%', desc: '' },
        { name: '捕捉球', rate: '7%', desc: '' },
        { name: '靈寵果實', rate: '5%', desc: '' },
        { name: '被搶劫', rate: '5%', desc: '損失50-200靈石' },
        { name: '低階法寶', rate: '3%', desc: '' },
        { name: '妖獸襲擊', rate: '3%', desc: '損失2%修爲' },
        { name: '高級靈石', rate: '0.5%', desc: 'x1' },
      ] },
    ],
  },

  // ===== 抽獎 =====
  gacha: {
    pools: [
      { id: 'normal', name: '普通池', cost: '300 靈石', desc: '入門獎勵', items: [
        { name: '靈石', rate: '34.5%', desc: '50-200' },
        { name: '高級靈石', rate: '0.5%', desc: 'x1' },
        { name: '練氣/築基靈草', rate: '20%', desc: '' },
        { name: '低階法寶', rate: '12%', desc: '15種' },
        { name: '練氣/築基丹藥', rate: '10%', desc: '' },
        { name: '捕捉球', rate: '8%', desc: '' },
        { name: '中階法寶', rate: '5%', desc: '' },
        { name: '靈寵果實', rate: '5%', desc: '' },
        { name: '低階資材', rate: '5%', desc: '鐵背蒼狼牙等' },
      ] },
      { id: 'premium', name: '高級池', cost: '1000 靈石', desc: '中高階獎勵', items: [
        { name: '靈石', rate: '19%', desc: '300-600' },
        { name: '高級靈石', rate: '1%', desc: 'x1' },
        { name: '結丹/元嬰靈草', rate: '18%', desc: '' },
        { name: '中階法寶', rate: '15%', desc: '18種' },
        { name: '結丹/元嬰丹藥', rate: '12%', desc: '' },
        { name: '高階法寶', rate: '10%', desc: '' },
        { name: '中階功法', rate: '8%', desc: '' },
        { name: '高階資材', rate: '7%', desc: '' },
        { name: '化神靈草', rate: '5%', desc: '天火芝等' },
        { name: '頂級靈寵果實', rate: '5%', desc: '' },
      ] },
      { id: 'lucky', name: '歐皇池', cost: '1 高級靈石', desc: '頂級獎勵', items: [
        { name: '天選之人', rate: '0.5%', desc: '獲得稱號「天選之人」' },
        { name: '頂級法寶', rate: '13.5%', desc: '獨一無二' },
        { name: '高階法寶', rate: '15%', desc: '' },
        { name: '元嬰/化神丹藥', rate: '12%', desc: '' },
        { name: '元嬰/化神靈草', rate: '12%', desc: '' },
        { name: '頂級功法', rate: '8%', desc: '' },
        { name: '高階功法', rate: '8%', desc: '' },
        { name: '化神-大乘丹藥', rate: '8%', desc: '' },
        { name: '頂級資材 x7', rate: '7%', desc: '' },
        { name: '中階資材/靈草/丹藥', rate: '10%', desc: '' },
        { name: '通天靈寶', rate: '1%', desc: '獨一無二' },
        { name: '頂級靈寵果實', rate: '5%', desc: '' },
      ] },
      { id: 'ultimate', name: '至尊歐皇池', cost: '5 高級靈石', desc: '通天靈寶高機率', items: [
        { name: '頂級法寶', rate: '20%', desc: '獨一無二' },
        { name: '頂級功法', rate: '15%', desc: '' },
        { name: '化神-大乘丹藥', rate: '20%', desc: '' },
        { name: '元嬰-大乘靈草', rate: '15%', desc: '' },
        { name: '頂級資材 x9', rate: '10%', desc: '' },
        { name: '高階法寶', rate: '10%', desc: '' },
        { name: '通天靈寶', rate: '10%', desc: '獨一無二' },
      ] },
    ],
  },

  // ===== 商城 =====
  shop: {
    refresh: '60 分鐘',
    normal: '練氣~結丹物品（靈草、丹藥、低中階法寶、資材、捕捉球）',
    high: '頂級物品（高階/頂級法寶、頂級靈草丹藥、究極球/大師球/頂級果實、可能出現通天靈寶）',
  },

  // ===== 煉器 =====
  forge: [
    { cost: '3 個低階資材', result: '隨機低階法寶', note: '' },
    { cost: '5 個中階資材', result: '隨機中階法寶', note: '' },
    { cost: '7 個高階資材', result: '隨機高階法寶', note: '' },
    { cost: '9 個頂級資材', result: '隨機頂級法寶', note: '失敗額外報廢1-2個資材' },
  ],
  forgeNote: '煉器失敗只損失三分之一材料（其餘退回）；頂級法寶為獨一無二，若已被他人取走，會改給 10000 靈石補償。',

  // ===== 靈寵 =====
  pets: [
    { name: '小金', rarity: '普通', base: '防禦+5%', evolve: '歐金金（防禦+10%）', penalty: 0 },
    { name: '小豪', rarity: '普通', base: '暴擊+2%', evolve: '嘉豪（暴擊+5%）', penalty: 0 },
    { name: '小馮', rarity: '普通', base: '生命+8%', evolve: '馮畜（生命+15%）', penalty: 0 },
    { name: '疾風', rarity: '普通', base: '遁速+10%', evolve: '颶風鼬（遁速+18%）', penalty: 0 },
    { name: '靈犀', rarity: '普通', base: '神識+8%', evolve: '千古靈犀（神識+15%）', penalty: 0 },
    { name: '修羅', rarity: '高級', base: '暴傷+10%', evolve: '聖光修羅→神照修羅王（暴傷+35%）', penalty: '捕捉-5%' },
    { name: '凱撒', rarity: '高級', base: '穿透+5%', evolve: '暗影凱撒→黯天凱撒皇（穿透+20%）', penalty: '捕捉-5%' },
    { name: '炎靈', rarity: '高級', base: '攻擊+10%', evolve: '赤炎→焚天炎皇（攻擊+30%）', penalty: '捕捉-5%' },
    { name: '玄龜', rarity: '高級', base: '防禦+12%', evolve: '鐵甲玄龜→不滅玄甲（防禦+35%）', penalty: '捕捉-5%' },
    { name: '雷靈', rarity: '高級', base: '暴擊+8%', evolve: '紫電雷靈→太初雷神（暴擊+25%）', penalty: '捕捉-5%' },
    { name: '小天', rarity: '真靈', base: '全屬性+20%', evolve: '帝天→黑龍王帝釋天（全+45%）', penalty: '捕捉-10%' },
    { name: '金猊', rarity: '真靈', base: '免疫+15%', evolve: '三眼金猊→帝皇瑞獸（免疫+35%）', penalty: '捕捉-10%' },
    { name: '小鳳', rarity: '真靈', base: '暴傷+15%', evolve: '鳳凰→涅槃鳳尊（暴傷+40%）', penalty: '捕捉-10%' },
    { name: '小龍', rarity: '真靈', base: '穿透+10%', evolve: '巨龍→九天真龍（穿透+30%）', penalty: '捕捉-10%' },
    { name: '幻靈', rarity: '真靈', base: '閃避+10%', evolve: '千幻→虛空幻主（閃避+30%）', penalty: '捕捉-10%' },
  ],
  petNote: '同時最多上陣 2 隻靈寵提供加成。捕捉球機率：普通球10%／高級球20%／超級球30%／究極球40%／大師球100%。餵食果實可進化，閃光形態 1% 機率屬性加成翻倍。',

  // ===== 主線 =====
  story: [
    { id: 1, title: '村口鼠精', realm: '練氣' },
    { id: 2, title: '媚骨花妖', realm: '練氣' },
    { id: 3, title: '雙頭色狼魔', realm: '練氣' },
    { id: 4, title: '豔舞狐', realm: '築基' },
    { id: 5, title: '楊春達', realm: '築基' },
    { id: 6, title: '萬獸谷三頭犬', realm: '築基' },
    { id: 7, title: '沉船魚', realm: '結丹' },
    { id: 8, title: '迷魂蝶精', realm: '結丹' },
    { id: 9, title: '雙修老魔', realm: '結丹' },
    { id: 10, title: '金太陽將軍', realm: '元嬰' },
    { id: 11, title: '幻影妖', realm: '元嬰' },
    { id: 12, title: '千面妖王', realm: '元嬰' },
    { id: 13, title: '凹胸仙人', realm: '化神' },
    { id: 14, title: '欲念石像', realm: '化神' },
    { id: 15, title: '慾魔尊者', realm: '化神' },
    { id: 16, title: '發情狼群', realm: '煉虛' },
    { id: 17, title: '鏡中妖', realm: '煉虛' },
    { id: 18, title: '鏡中妖王', realm: '煉虛' },
    { id: 19, title: '丁真', realm: '合體' },
    { id: 20, title: '雙修橋主', realm: '合體' },
    { id: 21, title: '千面橋神', realm: '合體' },
    { id: 22, title: '守門童子', realm: '大乘' },
    { id: 23, title: '幻境花', realm: '大乘' },
    { id: 24, title: '萬花妖后', realm: '大乘' },
    { id: 25, title: '馮媽', realm: '大乘' },
    { id: 26, title: '慾火石人', realm: '大乘' },
    { id: 27, title: '慾火尊者', realm: '大乘' },
    { id: 28, title: '情報小妖', realm: '大乘' },
    { id: 29, title: '最後的守衛', realm: '大乘' },
    { id: 30, title: '真相大反轉', realm: '大乘' },
  ],
  storyNote: '30 章主線劇情，每章挑戰對應境界 Boss，通關獲得靈石/靈草/丹藥/資材，特定章節掉落通天靈寶與頂級功法。',

  // ===== 副本 =====
  dungeons: [
    { name: '青木妖窟', realm: '練氣', boss: '木魁', note: '' },
    { name: '血霧沼澤', realm: '築基', boss: '毒蛟', note: '' },
    { name: '萬妖谷', realm: '結丹', boss: '妖皇', note: '' },
    { name: '幽冥鬼域', realm: '元嬰', boss: '幽冥鬼王', note: '' },
    { name: '焚天火域', realm: '化神', boss: '焚天老祖', note: '' },
    { name: '五行妖神谷', realm: '化神', boss: '金蛟王→土行孫子', note: '試煉：補全五行靈根' },
    { name: '虛空裂縫', realm: '煉虛', boss: '虛無之主', note: '' },
    { name: '古神遺跡', realm: '合體', boss: '殘存古神（誅仙四劍）', note: '' },
    { name: '九霄雷庭', realm: '大乘', boss: '太古雷帝（滅神矛）', note: '' },
  ],
  dungeonNote: '每個副本 3 關，首通豐厚獎勵，重複通關僅靈石。勝利後進入 30 分鐘冷卻。五行妖神谷為一次性試煉：五王各持隨機頂級法寶（獨一無二）+肉身加成，擊敗直接補全對應屬性靈根，全通即達成五行合一。',

  // ===== 丹方 =====
  alchemy: {
    rates: [
      { realm: '練氣', rate: '70%' }, { realm: '築基', rate: '60%' },
      { realm: '結丹', rate: '50%' }, { realm: '元嬰', rate: '40%' },
      { realm: '化神', rate: '30%' }, { realm: '煉虛', rate: '20%' },
      { realm: '合體', rate: '10%' }, { realm: '大乘', rate: '5%' },
    ],
    pills: [
      { name: '黃龍丹', tier: '練氣', usage: '練氣 1-4層', effect: '修爲+100', recipe: ['黃精草', '玉髓芝'], price: 600, type: '經驗' },
      { name: '金髓丸', tier: '練氣', usage: '練氣 5-8層', effect: '修爲+100', recipe: ['玉髓芝', '靈泉水'], price: 600, type: '經驗' },
      { name: '合氣丹', tier: '練氣', usage: '練氣 9-12層', effect: '修爲+100', recipe: ['黃精草', '靈泉水'], price: 600, type: '經驗' },
      { name: '築基丹', tier: '築基', usage: '練氣 12層', effect: '突破成功率+10%', recipe: ['金靈子', '血枸杞', '合歡花'], price: 900, type: '突破' },
      { name: '聚靈丹', tier: '築基', usage: '築基 初期', effect: '修爲+200', recipe: ['金靈子', '血枸杞'], price: 1000, type: '經驗' },
      { name: '血凝丹', tier: '築基', usage: '築基 初/中/後', effect: '修爲+800（副作用：最大生命-15%）', recipe: ['血枸杞', '合歡花'], price: 1000, type: '經驗' },
      { name: '固元丹', tier: '築基', usage: '築基 中期', effect: '修爲+300', recipe: ['金靈子', '合歡花', '靈泉水'], price: 1000, type: '經驗' },
      { name: '降塵丹', tier: '結丹', usage: '築基 後期', effect: '突破成功率+10%', recipe: ['地靈藤', '聚靈草', '紫猴花'], price: 1500, type: '突破' },
      { name: '五行凝元丹', tier: '結丹', usage: '結丹 初期', effect: '修爲+500', recipe: ['天靈果', '千年靈乳', '五行靈玉碎片'], price: 1800, type: '經驗' },
      { name: '三轉重元丹', tier: '結丹', usage: '結丹 中期', effect: '修爲+800', recipe: ['地靈藤', '紫猴花', '千年石鐘乳'], price: 1800, type: '經驗' },
      { name: '九轉還魂丹', tier: '結丹', usage: '結丹 後期', effect: '修爲+300｜突破+5%', recipe: ['天靈果', '血線蛟精血', '雪靈水'], price: 2500, type: '突破' },
      { name: '培嬰丹', tier: '結丹', usage: '結丹 後期', effect: '突破成功率+10%', recipe: ['養魂木枝葉', '九曲靈參', '千年石鐘乳'], price: 2600, type: '突破' },
      { name: '九轉還元丹', tier: '元嬰', usage: '元嬰 初期', effect: '修爲+1000', recipe: ['天靈花', '地元果', '萬年靈乳'], price: 3500, type: '經驗' },
      { name: '玉清丹', tier: '元嬰', usage: '元嬰 中期', effect: '修爲+1000', recipe: ['血精妖果', '玄天仙藤', '九葉芝'], price: 3500, type: '經驗' },
      { name: '太乙丹', tier: '元嬰', usage: '元嬰 後期', effect: '修爲+1200', recipe: ['陰陽玄龍草', '龍鱗果', '鳳血草'], price: 3500, type: '經驗' },
      { name: '造化丹', tier: '元嬰', usage: '元嬰 後期', effect: '修爲+1000｜突破+5%', recipe: ['幽冥花', '天靈花', '地元果', '陰陽玄龍草'], price: 5000, type: '突破' },
      { name: '化神丹', tier: '化神', usage: '元嬰 後期', effect: '突破成功率+15%', recipe: ['血精妖果', '玄天仙藤', '九葉芝', '陰陽玄龍草'], price: 5000, type: '突破' },
      { name: '天火丹', tier: '化神', usage: '化神 初期', effect: '修爲+1800', recipe: ['天火芝', '玄冰仙蓮'], price: 2000, type: '經驗' },
      { name: '玄冰丹', tier: '化神', usage: '化神 中期', effect: '修爲+1800', recipe: ['玄冰仙蓮', '九陽神參'], price: 2000, type: '經驗' },
      { name: '九陽神丹', tier: '化神', usage: '化神 後期', effect: '修爲+1800', recipe: ['天火芝', '九陽神參'], price: 2000, type: '經驗' },
      { name: '太虛丹', tier: '化神', usage: '化神 後期', effect: '突破成功率+7%', recipe: ['天火芝', '玄冰仙蓮', '九陽神參'], price: 6000, type: '突破' },
      { name: '金身丹', tier: '化神', usage: '化神 初/中/後', effect: '永久防禦+5%（限服2次）', recipe: ['天火芝', '玄冰仙蓮', '九陽神參'], price: 8000, type: '永久' },
      { name: '虛空丹', tier: '煉虛', usage: '煉虛 初期', effect: '修爲+2200', recipe: ['虛空花', '太陰月華'], price: 5000, type: '經驗' },
      { name: '太陰丹', tier: '煉虛', usage: '煉虛 中期', effect: '修爲+2300', recipe: ['太陰月華', '萬年玄參'], price: 5000, type: '經驗' },
      { name: '萬靈丹', tier: '煉虛', usage: '煉虛 後期', effect: '修爲+2400', recipe: ['虛空花', '萬年玄參'], price: 5000, type: '經驗' },
      { name: '虛無丹', tier: '煉虛', usage: '煉虛 後期', effect: '突破成功率+7%', recipe: ['虛空花', '太陰月華', '萬年玄參'], price: 15000, type: '突破' },
      { name: '虛靈丹', tier: '煉虛', usage: '煉虛 初/中/後', effect: '永久攻擊+5%（限服2次）', recipe: ['虛空花', '太陰月華', '萬年玄參'], price: 20000, type: '永久' },
      { name: '神合丹', tier: '合體', usage: '合體 初期', effect: '修爲+3000', recipe: ['神凰血芝', '龍魂草'], price: 12000, type: '經驗' },
      { name: '龍魂丹', tier: '合體', usage: '合體 中期', effect: '修爲+3100', recipe: ['龍魂草', '混沌果'], price: 12000, type: '經驗' },
      { name: '混沌丹', tier: '合體', usage: '合體 後期', effect: '修爲+3200', recipe: ['神凰血芝', '混沌果'], price: 12000, type: '經驗' },
      { name: '合道丹', tier: '合體', usage: '合體 後期', effect: '突破成功率+5%', recipe: ['神凰血芝', '龍魂草', '混沌果'], price: 35000, type: '突破' },
      { name: '神凰丹', tier: '合體', usage: '合體 初/中/後', effect: '永久神識+5%（限服2次）', recipe: ['神凰血芝', '龍魂草', '混沌果'], price: 50000, type: '永久' },
      { name: '天道丹', tier: '大乘', usage: '大乘 無', effect: '修爲+4000', recipe: ['鴻蒙紫氣果', '天道神葉'], price: 40000, type: '經驗' },
      { name: '無極丹', tier: '大乘', usage: '大乘 無', effect: '修爲+4200', recipe: ['天道神葉', '混沌青蓮'], price: 40000, type: '經驗' },
      { name: '渡劫丹', tier: '大乘', usage: '大乘 無', effect: '渡劫傷害-20%', recipe: ['鴻蒙紫氣果', '天道神葉', '混沌青蓮'], price: 80000, type: '突破' },
      { name: '鴻蒙丹', tier: '大乘', usage: '大乘 無', effect: '永久全屬性+3%（限服2次）', recipe: ['鴻蒙紫氣果', '天道神葉', '混沌青蓮'], price: 150000, type: '永久' },
    ],
    note: '依丹藥階級決定煉製成功率（越高階越難成丹）。服用需符合境界與小境界限制；「突破丹」於衝擊瓶頸時大幅提升成功率，「永久丹」服用後永久加成但有限次。',
  },

  // ===== 世界 Boss =====
  worldBoss: {
    desc: '每個境界各有一位全服共用的巨妖，同境界修仙者合力討伐。擊敗後 24 小時刷新，所有參與者皆獲相同獎勵。',
    rules: [
      '同境界才可參戰，每人每小時可攻擊一次（傷害累計保存）',
      '每次挑戰最多 20 回合，將本次削血轉為絕對傷害扣在共有血條上',
      '王以該境界最高靈力為根基蓄養血肉，攻防僅入門階段強度，並手持兩件法寶',
      '擊敗後進入 24 小時冷卻，重生時參與紀錄清空；尾刀者不多拿，全員同獎',
      '均衡目標：滿配同階戰士單場約削血 12~19%，需約 5-9 人合力',
    ],
    bosses: [
      { realm: '練氣', name: '陳友智', hp: 41679, mult: 11, tier: '低階', herbs: '黃精草、玉髓芝、靈泉水', materials: '鐵背蒼狼牙、玄冰蠶絲', pills: '黃龍丹、金髓丸、合氣丹', stones: '600~1000', high: false, people: 8 },
      { realm: '築基', name: '馬文康', hp: 42367, mult: 2.2, tier: '中階', herbs: '金靈子、血枸杞、合歡花', materials: '鐵背蒼狼牙、百年火蟒鱗', pills: '聚靈丹、固元丹', stones: '2000~3500', high: false, people: 8 },
      { realm: '結丹', name: '蔡樂懷', hp: 787595, mult: 7.1, tier: '高階', herbs: '地靈藤、紫猴花、千年靈乳、天靈果', materials: '金角犀獨角、千年寒鐵母', pills: '降塵丹', stones: '4000~6500', high: false, people: 8 },
      { realm: '元嬰', name: '思維老祖', hp: 4459406, mult: 6.7, tier: '高階', herbs: '龍鱗果、幽冥花、萬年靈乳', materials: '千年寒鐵母、噬魂蝶鱗粉', pills: '培嬰丹', stones: '8000~12000', high: true, people: 8 },
      { realm: '化神', name: '狗王堅', hp: 5110401, mult: 1.55, tier: '頂級', herbs: '天火芝、玄冰仙蓮、九陽神參', materials: '天雷鵬骨、地心火龍鱗', pills: '太虛丹', stones: '14000~20000', high: true, people: 7 },
      { realm: '煉虛', name: '唐三', hp: 443305335, mult: 27.5, tier: '頂級', herbs: '虛空花、太陰月華、萬年玄參', materials: '千年屍王心核、地心火龍鱗', pills: '虛無丹', stones: '24000~34000', high: true, people: 9 },
      { realm: '合體', name: '老馮畜', hp: 11158177315, mult: 145, tier: '通天靈寶', herbs: '鴻蒙紫氣果、天道神葉、混沌青蓮', materials: '太古真龍逆鱗、萬載玄龜甲', pills: '合道丹', stones: '38000~54000', high: true, people: 5 },
      { realm: '大乘', name: '馮問老母分身', hp: 8926541910, mult: 58, tier: '通天靈寶', herbs: '鴻蒙紫氣果、天道神葉、混沌青蓮', materials: '鳳凰涅槃羽、萬載玄龜甲', pills: '渡劫丹', stones: '58000~80000', high: true, people: 5 },
    ],
    note: '獎勵人人相同：抽 2 種靈草各 x2、1 種資材 x1、1 顆丹藥、隨機靈石；元嬰以上王額外加「高級靈石 x1」。王所持法寶僅供自身加成，擊殺不掉落。',
  },

  // ===== 特殊效果（狀態）=====
  effects: [
    { icon: '🔥', name: '燃燒', desc: '每回合損失最大生命% 傷害，可疊加' },
    { icon: '☠️', name: '中毒', desc: '每回合損失最大生命% 傷害' },
    { icon: '🩸', name: '流血', desc: '每回合損失最大生命% 傷害' },
    { icon: '🕯️', name: '詛咒', desc: '每回合損血並降低攻擊力' },
    { icon: '❄️', name: '冰凍', desc: '該回合無法行動，額外受20%傷害' },
    { icon: '⚡', name: '麻痹', desc: '該回合無法行動' },
    { icon: '💤', name: '睡眠', desc: '該回合無法行動' },
    { icon: '💢', name: '震懾', desc: '無法行動，下回合傷害-30%' },
    { icon: '🥀', name: '虛弱', desc: '造成傷害減半' },
    { icon: '⚔️', name: '破甲', desc: '無視防禦%' },
    { icon: '🛡️', name: '護盾', desc: '抵擋固定%最大生命傷害' },
    { icon: '💚', name: '癒合/回血', desc: '每回合回復生命' },
    { icon: '📉', name: '降攻', desc: '攻擊力降低%' },
    { icon: '🌀', name: '混亂', desc: '該回合攻擊隨機目標' },
    { icon: '🧷', name: '定身', desc: '無法行動（對BOSS無效）' },
    { icon: '🔒', name: '封印', desc: '無法行動數回合（對BOSS無效）' },
    { icon: '🗻', name: '鎮壓', desc: '被收入圖中，每回合受10%最大生命傷害' },
    { icon: '👹', name: '法相/變身', desc: '攻擊翻倍+吸血，或隨機五行增益' },
    { icon: '🪞', name: '複製增益', desc: '複製對方最後一個增益' },
    { icon: '💀', name: '斬殺', desc: '生命低於閾值直接擊殺（對BOSS無效）' },
    { icon: '⏳', name: '時間加速', desc: '該回合可行動兩次' },
    { icon: '✨', name: '淨化', desc: '驅散自身所有負面效果' },
    { icon: '🩸', name: '吸血', desc: '回復造成傷害%的生命' },
    { icon: '🪄', name: '驅散', desc: '清除對方所有增益效果' },
    { icon: '🌩️', name: '渡劫', desc: '大乘飛升需扛過九道天劫' },
  ],

  // ===== 玩法流程 =====
  gameplay: [
    { title: '註冊與靈根', desc: '輸入道號註冊，隨機獲得靈根（天/一般/偽），決定修練速度與功法屬性' },
    { title: '修練與簽到', desc: '每 3 分鐘可修練一次獲得修爲（靈根倍率 x 加成），簽到領取資源' },
    { title: '突破境界', desc: '修爲達瓶頸即可突破，成功率依境界遞減；元嬰前有心魔劫、煉虛需五行合一、真仙需渡雷劫' },
    { title: '副本征伐', desc: '依境界挑戰副本（9 個），30 分鐘冷卻，首通豐厚' },
    { title: '主線劇情', desc: '30 章冒險故事，一路從村口打到大乘' },
    { title: '煉丹與種植', desc: '採集靈草煉丹（有成功率），種植靈草加速獲取' },
    { title: '煉器', desc: '用妖獸資材打造法寶，階級越高成功率越低' },
    { title: '商城交易', desc: '每 60 分鐘刷新庫存，普通/高級商城，頂級法寶先到先得' },
    { title: '抽獎', desc: '四個獎池，通天靈寶與頂級法寶獨一無二' },
    { title: '奇遇', desc: '每 6 小時一次隨機際遇，可能一夜暴富也可能被搶' },
    { title: '靈寵養成', desc: '捕捉球捕捉 15 種靈寵，餵果實進化，上陣 2 隻加成' },
    { title: '切磋 PVP', desc: '與其他修仙者一對一切磋，勝利獲得突破感悟（上限+5%）' },
    { title: '功法主副系統', desc: '主功法全效、副功法半效，屬性需對應靈根' },
    { title: '稱號系統', desc: '達成境界/成就獲得稱號，部分帶屬性加成（如幸運星+20%修練）' },
    { title: '世界Boss', desc: '同境界合力討伐全服共有的巨妖，擊敗後 24 小時重生，人人同獎' },
  ],
};

if (typeof module !== 'undefined') module.exports = DATA;
